// src/Reconciliation.Angular/ClientApp/src/app/home/home.component.ts
import { Component, Inject, Injector, OnInit, ViewChild, ElementRef } from '@angular/core';
import { HttpClient } from "@angular/common/http";
import { AppComponentBase } from '../shared/app-component-base';
import { ReconciliationListDto } from './models/dtos/reconciliation-list-dto.model';
import { YearlyReconciliationGridColumnDto } from './models/dtos/yearly-reconsiliation-grid-dto.model';
import { ReconciliationFormDto } from './models/dtos/reconciliation-form-dto.model';
import { finalize } from 'rxjs/operators';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent extends AppComponentBase implements OnInit {

  @ViewChild("amountInput", { static: false }) amountInput: ElementRef;

  grid: ReconciliationListDto[];
  isEditing: boolean = false;
  editingRow: number;
  editingCol: number;

  constructor(injector: Injector) {
    super(injector);

  }

  ngOnInit(): void {
    this.getYearlyTable();
  }


  getYearlyTable() {
    this.httpClient.get<ReconciliationListDto[]>(this.baseUrl + 'reconciliation/yearly-table')
      .subscribe(result => {
        this.grid = result;
      }, error => console.error(error));
  }

  editCell(row: number, col: number) {
    if (this.isSaving) return;

    this.isEditing = true;
    this.editingRow = row;
    this.editingCol = col;

    setTimeout(() => {
      this.amountInput.nativeElement.focus();
    }, 100)
  }

  saveOrUpdate(column: YearlyReconciliationGridColumnDto) {

    let input = new ReconciliationFormDto();
    input.id = column.id;
    input.incomeOrExpenseTypeId = column.incomeOrExpenseTypeId;
    input.month = column.month;
    input.year = column.year;
    input.amount = column.amount;

    this.isSaving = true;
    this.httpClient.put(this.baseUrl + 'reconciliation', input)
      .pipe(finalize(() => { this.isSaving = false }))
      .subscribe(result => {
        this.getYearlyTable();

        this.resetCell();
      }, error => {
        console.error(error);
      });
  }

  resetCell() {
    this.isEditing = false;
    this.editingRow = undefined;
    this.editingCol = undefined;
  }

}

<p *ngIf="!grid" class="text-center"><em>Loading...</em></p>

<h6 class="text-center">We are in Angular App</h6>

<table class='table table-striped table-hover table-bordered' aria-labelledby="tableLabel" *ngIf="grid">
  <thead>
    <tr>
      <th colspan="13" class="text-center">Year {{grid.year}}</th>
    </tr>
    <tr>
      <th></th>
      <th *ngFor="let title of grid.titles">{{title.monthDisplayName}}</th>
    </tr>
  </thead>
  <tbody>

    <!-- printing readonly statements -->
    <tr *ngFor="let row of grid.statements" class="table-secondary">
      <td>{{ row.title }}</td>

      <td *ngFor="let col of row.values">{{ col.amount }}</td>
    </tr>


    <!-- printing reconciliation -->
    <tr>
      <th colspan="13" class="text-center">Reconciliation</th>
    </tr>
    <tr *ngFor="let row of grid.rows; index as rowIndex;"
      [ngClass]="{'table-success': row.flag==1, 'table-danger': row.flag==2}">
      <td>{{ row.incomeOrExpenseTypeName }}</td>

      <ng-container *ngFor="let col of row.columns; index as colIndex;">

        <td (click)="editCell(rowIndex, colIndex)"
          *ngIf="!isEditing || isEditing && (editingRow!=rowIndex || editingCol!=colIndex)" title="Click to edit"
          class="pointer">{{ col.amount }}</td>

        <td *ngIf="isEditing && editingRow==rowIndex  && editingCol==colIndex">
          <form (ngSubmit)="saveOrUpdate(col)">
            <input type="number" [(ngModel)]="col.amount" name="amount" (blur)="resetCell()" #amountInput title="Press enter to update" class="edit-input-size"/>
          </form>
        </td>

      </ng-container>

    </tr>


    <!-- printing result -->
    <tr *ngFor="let row of grid.results" class="table-secondary">
      <th>{{ row.title }}</th>

      <th *ngFor="let col of row.values">{{ col.amount }}</th>
    </tr>

  </tbody>
</table>

<div class="row mb-5">
  <div class="col-12 text-center">
    <span class="badge badge-secondary">Readonly</span>
    &nbsp;&nbsp;
    <span class="badge badge-success">Income</span>
    &nbsp;&nbsp;
    <span class="badge badge-danger">Expense</span>
  </div>
</div>

// src/Reconciliation.React/ClientApp/src/components/Home.js
import React, { Component } from 'react';


export class Home extends Component {
    static displayName = Home.name;

    constructor(props) {
        super(props);
        this.state = { grid: undefined, loading: true, isEditing: false, cell: undefined, editRowIndex: undefined, editColIndex: undefined, editAmount: undefined };

        this.handleEditCellClick = this.handleCellEditClick.bind(this);
        this.handleResetCellEditClick = this.handleResetCellEditClick.bind(this);

        this.handleChange = this.handleChange.bind(this);
        this.handleSubmit = this.handleSubmit.bind(this);
    }


    componentDidMount() {
        this.populateReconciliationGrid();
    }


    handleCellEditClick(cell, rowIndex, colIndex) {
        this.setState({
            isEditing: true,
            cell: cell,
            editRowIndex: rowIndex,
            editColIndex: colIndex,
            editAmount: cell.amount,
        });
    }

    handleResetCellEditClick(event) {
        this.setState({ isEditing: false });
    }



    handleChange(event) {
        this.setState({ editAmount: event.target.value });
    }

    handleSubmit(event) {
        this.updateReconciliationCell();
        this.handleResetCellEditClick();
        event.preventDefault();
    }



    static renderReconciliationTableTitles(titles) {
        return (
            titles.map((item, index) => {
                return <td key={item.month}>{item.monthDisplayName}</td>
            })
        );
    }


    static renderReconciliationTableStatementsOrResults(statementsOrResults, className) {
        return (
            statementsOrResults.map((row, index) => {
                return <tr className={className} key={row.title}>
                    <td>{row.title}</td>
                    {row.values.map(col => {
                        return <td key={col.month}>{col.amount}</td>
                    })}
                </tr>
            })
        );
    }

    static renderReconciliationTableEditableRows(rows, self) {

        return (
            rows.map((row, rowIndex) => {
                return <tr key={row.incomeOrExpenseTypeName} className={row.flag == 1 ? 'table-success' : 'table-danger'}>
                    <td>{row.incomeOrExpenseTypeName}</td>
                    {row.columns.map((col, colIndex) => {

                        let props = {
                            rowIndex: rowIndex,
                            colIndex: colIndex,
                            col: col,
                            tdOnClick: self.handleEditCellClick,
                            formOnSubmit: self.handleSubmit,
                            formOnChange: self.handleChange,
                            formOnBlur: self.handleResetCellEditClick,
                            state: self.state,
                        };

                        return <EditableTableCell key={col.month} {...props} />
                    })}
                </tr>
            })
        );
    }


    static renderReconciliationTable(grid, self) {
        return (
            <table className='table table-striped table-bordered' aria-labelledby="tabelLabel">
                <thead>
                    <tr className="text-center">
                        <th colSpan="14">Year {grid.year}</th>
                    </tr>
                    <tr>
                        <td></td>
                        {Home.renderReconciliationTableTitles(grid.titles)}
                    </tr>
                </thead>

                <tbody>
                    {Home.renderReconciliationTableStatementsOrResults(grid.statements, 'table-secondary')}

                    {Home.renderReconciliationTableEditableRows(grid.rows, self)}

                    {Home.renderReconciliationTableStatementsOrResults(grid.results, 'table-warning')}
                </tbody>
            </table>
        );
    }

    render() {

        let contents = this.state.loading
            ? <p><em>Loading...</em></p>
            : Home.renderReconciliationTable(this.state.grid, this);

        return (
            <div>
                <h6 id="tabelLabel" className="text-center">We are in React App</h6>

                {contents}


                <div className="row mb-5">
                    <div className="col-12 text-center">
                        <span className="badge badge-secondary">Readonly</span>
                        &nbsp;&nbsp;
                        <span className="badge badge-success">Income</span>
                        &nbsp;&nbsp;
                        <span className="badge badge-danger">Expense</span>
                    </div>
                </div>
            </div>


        );

    }

    async populateReconciliationGrid() {
        const response = await fetch('reconciliation/yearly-table');
        const data = await response.json();
        this.setState({ grid: data, loading: false });
    }

    async updateReconciliationCell() {

        let cell = this.state.cell;
        cell.amount = +this.state.editAmount;

        const requestOptions = {
            method: 'PUT',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(cell)
        };

        //this.setState({ loading: true });
        const response = await fetch('reconciliation', requestOptions);
        //await response.json();
        //this.setState({ loading: false });

        await this.populateReconciliationGrid();
    }

}

function ViewTableCell(props) {
    return (
        <td className='pointer' title='Click to edit' onClick={() => props.tdOnClick(props.col, props.rowIndex, props.colIndex)}>{props.col.amount}</td>
    )
}

function FormTableCell(props) {
    return (
        <td>
            <form onSubmit={props.formOnSubmit}>
                <input className='edit-input-size' title='Press enter to update' type="text" value={props.state.editAmount} onChange={props.formOnChange} onBlur={props.formOnBlur} required />
            </form>
        </td>
    )
}

function EditableTableCell(props) {
    const isView = !props.state.isEditing || props.state.isEditing && (+props.state.editRowIndex != props.rowIndex || +props.state.editColIndex != props.colIndex);
    if (isView) {
        return <ViewTableCell {...props} />;
    }
    return <FormTableCell {...props} />;
}
